import type {
  AdvancedFeatureModule,
  Alert,
  AnomalyEvent,
  ComplianceEntry,
  ConnectorStatus,
  CustomKpi,
  DemoData,
  Equipment,
  EnergyRecord,
  GenealogyRecord,
  HistoricalPoint,
  InventoryItem,
  InnovationIdea,
  MaintenancePrediction,
  OperatorMetric,
  OptimizationRecommendation,
  ProductionLine,
  ProductionPlanItem,
  QualityEvent,
  RootCauseCase,
  SitePerformance,
  ShiftHandoverReport,
  SpcSample,
} from "@/lib/types";
import { formatNumber, formatPercent } from "@/lib/utils";

const facility = {
  id: "facility-atlas",
  name: "Atlas Components Plant",
  location: "Detroit, MI",
  shift: "Day Shift · 06:00-14:00",
};

export const demoSites: SitePerformance[] = [
  {
    facilityId: "facility-atlas",
    facilityName: "Atlas Components Plant",
    location: "Detroit, MI",
    lineCount: 3,
    oee: 87.8,
    throughput: 814,
    openAlerts: 2,
    status: "watch",
  },
  {
    facilityId: "facility-orion",
    facilityName: "Orion Plastics Hub",
    location: "Austin, TX",
    lineCount: 4,
    oee: 91.9,
    throughput: 1116,
    openAlerts: 1,
    status: "strong",
  },
  {
    facilityId: "facility-nova",
    facilityName: "Nova Finishing Center",
    location: "Columbus, OH",
    lineCount: 2,
    oee: 79.6,
    throughput: 392,
    openAlerts: 4,
    status: "risk",
  },
];

export const demoConnectors: ConnectorStatus[] = [
  {
    id: "conn-opcua-atlas",
    facilityId: "facility-atlas",
    name: "Atlas OPC-UA Gateway",
    protocol: "OPC-UA",
    status: "healthy",
    latencyMs: 170,
    recordsPerMin: 4200,
    lastIngestedAt: "2026-03-14T06:58:00Z",
    notes: "Primary PLC and press telemetry stream.",
  },
  {
    id: "conn-mqtt-orion",
    facilityId: "facility-orion",
    name: "Orion Edge MQTT Broker",
    protocol: "MQTT",
    status: "degraded",
    latencyMs: 540,
    recordsPerMin: 2980,
    lastIngestedAt: "2026-03-14T06:55:00Z",
    notes: "Intermittent packet delay from line 2 scanner cluster.",
  },
  {
    id: "conn-rest-nova",
    facilityId: "facility-nova",
    name: "Nova MES REST Sync",
    protocol: "REST",
    status: "offline",
    latencyMs: 0,
    recordsPerMin: 0,
    lastIngestedAt: "2026-03-14T04:12:00Z",
    notes: "MES token expired. Re-authentication required.",
  },
];

export const demoKpis: CustomKpi[] = [
  {
    id: "kpi-energy-per-unit",
    facilityId: "facility-atlas",
    name: "Energy per Unit",
    formula: "total_energy_kwh / good_units",
    targetValue: 2.3,
    currentValue: 2.6,
    unit: "kWh/unit",
  },
  {
    id: "kpi-unplanned-downtime-rate",
    facilityId: "facility-atlas",
    name: "Unplanned Downtime Rate",
    formula: "unplanned_minutes / shift_minutes",
    targetValue: 5,
    currentValue: 7.2,
    unit: "%",
  },
  {
    id: "kpi-quality-cost-index",
    facilityId: "facility-atlas",
    name: "Quality Cost Index",
    formula: "(rework_cost + scrap_cost) / output_value",
    targetValue: 3.5,
    currentValue: 2.9,
    unit: "%",
  },
];

export const demoAnomalies: AnomalyEvent[] = [
  {
    id: "anomaly-001",
    facilityId: "facility-atlas",
    equipmentId: "eq-robot-12",
    signal: "Cycle variance burst",
    severity: "high",
    anomalyScore: 92,
    status: "reviewing",
    detectedAt: "2026-03-14T06:42:00Z",
    summary: "Cycle variance exceeded baseline by 3.4 sigma for 11 consecutive runs.",
  },
  {
    id: "anomaly-002",
    facilityId: "facility-atlas",
    equipmentId: "eq-oven-03",
    signal: "Thermal oscillation",
    severity: "critical",
    anomalyScore: 97,
    status: "new",
    detectedAt: "2026-03-14T06:31:00Z",
    summary: "Temperature control loop entered oscillation outside normal control bounds.",
  },
  {
    id: "anomaly-003",
    facilityId: "facility-orion",
    equipmentId: "eq-orion-11",
    signal: "Sensor drift",
    severity: "medium",
    anomalyScore: 68,
    status: "resolved",
    detectedAt: "2026-03-14T05:09:00Z",
    summary: "Edge calibration recalibration restored normal signal profile.",
  },
];

export const demoHistoricalPoints: HistoricalPoint[] = [
  { id: "hist-001", lineId: "line-alpha", metric: "oee", value: 91.2, recordedAt: "2026-03-14T04:00:00Z" },
  { id: "hist-002", lineId: "line-alpha", metric: "oee", value: 92.1, recordedAt: "2026-03-14T05:00:00Z" },
  { id: "hist-003", lineId: "line-alpha", metric: "oee", value: 93.2, recordedAt: "2026-03-14T06:00:00Z" },
  { id: "hist-004", lineId: "line-bravo", metric: "throughput", value: 252, recordedAt: "2026-03-14T04:00:00Z" },
  { id: "hist-005", lineId: "line-bravo", metric: "throughput", value: 264, recordedAt: "2026-03-14T05:00:00Z" },
  { id: "hist-006", lineId: "line-bravo", metric: "throughput", value: 274, recordedAt: "2026-03-14T06:00:00Z" },
  { id: "hist-007", lineId: "line-charlie", metric: "defect_rate", value: 4.4, recordedAt: "2026-03-14T04:00:00Z" },
  { id: "hist-008", lineId: "line-charlie", metric: "defect_rate", value: 4.0, recordedAt: "2026-03-14T05:00:00Z" },
  { id: "hist-009", lineId: "line-charlie", metric: "defect_rate", value: 3.7, recordedAt: "2026-03-14T06:00:00Z" },
];

export const demoPlans: ProductionPlanItem[] = [
  {
    id: "plan-001",
    facilityId: "facility-atlas",
    workOrder: "WO-AT-240314-01",
    product: "Rotor Housing",
    assignedLine: "line-alpha",
    targetUnits: 2400,
    plannedStart: "2026-03-14T06:00:00Z",
    plannedEnd: "2026-03-14T14:00:00Z",
    status: "in_progress",
  },
  {
    id: "plan-002",
    facilityId: "facility-atlas",
    workOrder: "WO-AT-240314-02",
    product: "Actuator Bracket",
    assignedLine: "line-bravo",
    targetUnits: 1800,
    plannedStart: "2026-03-14T07:00:00Z",
    plannedEnd: "2026-03-14T15:00:00Z",
    status: "scheduled",
  },
  {
    id: "plan-003",
    facilityId: "facility-nova",
    workOrder: "WO-NV-240314-05",
    product: "Surface Seal Assembly",
    assignedLine: "line-nova-1",
    targetUnits: 950,
    plannedStart: "2026-03-14T05:30:00Z",
    plannedEnd: "2026-03-14T13:30:00Z",
    status: "delayed",
  },
];

export const demoEnergy: EnergyRecord[] = [
  {
    id: "energy-001",
    facilityId: "facility-atlas",
    lineId: "line-alpha",
    kwh: 892,
    intensityKwhPerUnit: 2.4,
    peakKw: 152,
    recordedAt: "2026-03-14T06:00:00Z",
  },
  {
    id: "energy-002",
    facilityId: "facility-atlas",
    lineId: "line-bravo",
    kwh: 774,
    intensityKwhPerUnit: 2.8,
    peakKw: 141,
    recordedAt: "2026-03-14T06:00:00Z",
  },
  {
    id: "energy-003",
    facilityId: "facility-orion",
    lineId: "line-orion-2",
    kwh: 1104,
    intensityKwhPerUnit: 1.9,
    peakKw: 188,
    recordedAt: "2026-03-14T06:00:00Z",
  },
];

export const demoInventory: InventoryItem[] = [
  {
    id: "inv-001",
    sku: "RM-AL-221",
    name: "Aluminum Coil 2.2mm",
    category: "raw_material",
    onHand: 1480,
    wip: 0,
    finishedGoods: 0,
    reorderPoint: 900,
    status: "healthy",
  },
  {
    id: "inv-002",
    sku: "WIP-BR-100",
    name: "Bracket Semi-Finished",
    category: "wip",
    onHand: 0,
    wip: 420,
    finishedGoods: 0,
    reorderPoint: 250,
    status: "watch",
  },
  {
    id: "inv-003",
    sku: "FG-RH-500",
    name: "Rotor Housing Final",
    category: "finished_good",
    onHand: 320,
    wip: 0,
    finishedGoods: 320,
    reorderPoint: 500,
    status: "critical",
  },
];

export const demoOperators: OperatorMetric[] = [
  {
    id: "op-001",
    operatorName: "Nina Patel",
    shift: "Day",
    efficiency: 94,
    safetyIncidents: 0,
    trainingGap: "low",
    status: "strong",
  },
  {
    id: "op-002",
    operatorName: "Liam Chen",
    shift: "Swing",
    efficiency: 86,
    safetyIncidents: 1,
    trainingGap: "medium",
    status: "watch",
  },
  {
    id: "op-003",
    operatorName: "Marta Rivera",
    shift: "Night",
    efficiency: 78,
    safetyIncidents: 2,
    trainingGap: "high",
    status: "needs_support",
  },
];

export const demoOptimizations: OptimizationRecommendation[] = [
  {
    id: "opt-001",
    lineId: "line-alpha",
    parameter: "Press force setpoint",
    currentValue: 72,
    recommendedValue: 69,
    expectedGainPercent: 3.4,
    confidence: 87,
    status: "ready",
  },
  {
    id: "opt-002",
    lineId: "line-bravo",
    parameter: "Robot dwell time",
    currentValue: 1.8,
    recommendedValue: 1.5,
    expectedGainPercent: 6.9,
    confidence: 83,
    status: "testing",
  },
  {
    id: "opt-003",
    lineId: "line-charlie",
    parameter: "Oven zone 2 temp",
    currentValue: 214,
    recommendedValue: 208,
    expectedGainPercent: 4.1,
    confidence: 79,
    status: "applied",
  },
];

export const demoRootCauses: RootCauseCase[] = [
  {
    id: "rca-001",
    alertId: "alert-001",
    issue: "Oven zone 2 overheating",
    probableCause: "Exhaust fan bearing wear causing reduced airflow.",
    confidence: 91,
    recommendedAction: "Replace fan cartridge and re-balance zone control loop.",
    status: "open",
  },
  {
    id: "rca-002",
    alertId: "alert-002",
    issue: "Assembly cycle drift",
    probableCause: "Axis 3 backlash after extended high-load sequence.",
    confidence: 84,
    recommendedAction: "Run calibration routine and inspect coupling.",
    status: "validated",
  },
];

export const demoShiftReports: ShiftHandoverReport[] = [
  {
    id: "shift-001",
    facilityId: "facility-atlas",
    shiftName: "Day Shift",
    startAt: "2026-03-14T06:00:00Z",
    endAt: "2026-03-14T14:00:00Z",
    summary: "Stable output with one critical thermal escalation handled in progress.",
    oee: 89.4,
    throughput: 814,
    incidents: 1,
    handoverNote: "Prioritize oven airflow inspection at 14:30 maintenance window.",
  },
  {
    id: "shift-002",
    facilityId: "facility-orion",
    shiftName: "Swing Shift",
    startAt: "2026-03-14T14:00:00Z",
    endAt: "2026-03-14T22:00:00Z",
    summary: "Strong throughput, one connector degradation under monitoring.",
    oee: 91.7,
    throughput: 1116,
    incidents: 0,
    handoverNote: "Verify MQTT broker packet loss after shift start.",
  },
];

export const demoCompliance: ComplianceEntry[] = [
  {
    id: "comp-001",
    standard: "ISO 9001",
    area: "Quality management",
    owner: "QA Lead",
    dueDate: "2026-03-30",
    status: "compliant",
    evidenceLink: "https://example.com/evidence/iso9001",
  },
  {
    id: "comp-002",
    standard: "OSHA 1910",
    area: "Machine guarding",
    owner: "Safety Manager",
    dueDate: "2026-03-20",
    status: "at_risk",
    evidenceLink: "https://example.com/evidence/osha1910",
  },
  {
    id: "comp-003",
    standard: "FDA 21 CFR Part 11",
    area: "Electronic records",
    owner: "Compliance Officer",
    dueDate: "2026-03-18",
    status: "non_compliant",
    evidenceLink: "https://example.com/evidence/part11",
  },
];

export const demoGenealogy: GenealogyRecord[] = [
  {
    id: "gen-001",
    batchCode: "AT-240314-A",
    product: "Rotor Housing",
    parentBatch: "RM-AL-221-778",
    equipmentPath: "Servo Press 07 -> Robot Cell 12 -> Vision Station 04",
    qualityStatus: "pass",
    startedAt: "2026-03-14T04:10:00Z",
    completedAt: "2026-03-14T05:52:00Z",
  },
  {
    id: "gen-002",
    batchCode: "AT-240314-C",
    product: "Seal Assembly",
    parentBatch: "RM-SEAL-443-102",
    equipmentPath: "Robot Cell 12 -> Cure Oven 03 -> Vision Station 04",
    qualityStatus: "hold",
    startedAt: "2026-03-14T04:24:00Z",
    completedAt: "2026-03-14T06:05:00Z",
  },
];

export const demoSpc: SpcSample[] = [
  {
    id: "spc-001",
    lineId: "line-alpha",
    parameter: "Press thickness",
    sampleValue: 2.24,
    mean: 2.2,
    lcl: 2.1,
    ucl: 2.3,
    status: "in_control",
    sampledAt: "2026-03-14T06:45:00Z",
  },
  {
    id: "spc-002",
    lineId: "line-bravo",
    parameter: "Torque output",
    sampleValue: 41.8,
    mean: 40.0,
    lcl: 37.5,
    ucl: 42.0,
    status: "warning",
    sampledAt: "2026-03-14T06:47:00Z",
  },
  {
    id: "spc-003",
    lineId: "line-charlie",
    parameter: "Cure temperature",
    sampleValue: 216.4,
    mean: 208.0,
    lcl: 203.0,
    ucl: 214.0,
    status: "out_of_control",
    sampledAt: "2026-03-14T06:49:00Z",
  },
];

export const demoAdvancedModules: AdvancedFeatureModule[] = [
  {
    id: "adv-001",
    slug: "ai-powered-production-optimization",
    name: "AI-Powered Production Optimization",
    description:
      "Continuously optimizes schedules and resource allocation against real-time plant constraints.",
    priority: "innovative",
    complexity: "high",
    adoptionPercent: 44,
    latencyMs: 420,
    roiPercent: 11.8,
    status: "pilot",
    recommendation: "Roll out in Atlas + Orion with closed-loop schedule controls.",
  },
  {
    id: "adv-002",
    slug: "augmented-reality-maintenance",
    name: "Augmented Reality Maintenance",
    description: "AR-guided maintenance workflows with real-time equipment overlays.",
    priority: "innovative",
    complexity: "high",
    adoptionPercent: 27,
    latencyMs: 180,
    roiPercent: 8.2,
    status: "pilot",
    recommendation: "Start with thermal and robotic asset classes for highest downtime reduction.",
  },
  {
    id: "adv-003",
    slug: "digital-factory-simulation",
    name: "Digital Factory Simulation",
    description: "What-if process simulation on digital twin models prior to physical changes.",
    priority: "important",
    complexity: "high",
    adoptionPercent: 52,
    latencyMs: 900,
    roiPercent: 13.4,
    status: "active",
    recommendation: "Use for weekly planning and process change reviews.",
  },
  {
    id: "adv-004",
    slug: "autonomous-quality-control",
    name: "Autonomous Quality Control",
    description: "Computer-vision defect detection and classification at line speed.",
    priority: "important",
    complexity: "high",
    adoptionPercent: 49,
    latencyMs: 140,
    roiPercent: 12.1,
    status: "active",
    recommendation: "Expand model coverage to packaging and finishing stations.",
  },
  {
    id: "adv-005",
    slug: "supply-chain-integration",
    name: "Supply Chain Integration",
    description: "Supplier visibility and synchronized material risk monitoring.",
    priority: "important",
    complexity: "high",
    adoptionPercent: 41,
    latencyMs: 680,
    roiPercent: 9.8,
    status: "pilot",
    recommendation: "Prioritize critical suppliers with high stockout impact.",
  },
  {
    id: "adv-006",
    slug: "edge-ai-processing",
    name: "Edge AI Processing",
    description: "Low-latency model execution directly on factory-floor devices.",
    priority: "innovative",
    complexity: "high",
    adoptionPercent: 36,
    latencyMs: 28,
    roiPercent: 10.7,
    status: "active",
    recommendation: "Move anomaly and quality classifiers to edge nodes where feasible.",
  },
  {
    id: "adv-007",
    slug: "natural-language-query-interface",
    name: "Natural Language Query Interface",
    description: "Conversational interface for querying production and quality metrics.",
    priority: "innovative",
    complexity: "high",
    adoptionPercent: 31,
    latencyMs: 520,
    roiPercent: 7.9,
    status: "pilot",
    recommendation: "Enable governed prompts for plant managers first.",
  },
  {
    id: "adv-008",
    slug: "blockchain-quality-certificates",
    name: "Blockchain Quality Certificates",
    description: "Immutable provenance and quality certificates for downstream trust.",
    priority: "innovative",
    complexity: "high",
    adoptionPercent: 19,
    latencyMs: 1500,
    roiPercent: 4.5,
    status: "planned",
    recommendation: "Restrict to regulated products where audit value is highest.",
  },
  {
    id: "adv-009",
    slug: "collaborative-robot-integration",
    name: "Collaborative Robot Integration",
    description: "Direct cobot coordination and performance tuning with line controls.",
    priority: "important",
    complexity: "high",
    adoptionPercent: 46,
    latencyMs: 95,
    roiPercent: 9.2,
    status: "active",
    recommendation: "Synchronize cobot cycle models with line throughput planning.",
  },
  {
    id: "adv-010",
    slug: "carbon-footprint-tracking",
    name: "Carbon Footprint Tracking",
    description: "Real-time emissions and sustainability impact accounting by process.",
    priority: "important",
    complexity: "medium",
    adoptionPercent: 58,
    latencyMs: 260,
    roiPercent: 6.7,
    status: "active",
    recommendation: "Integrate energy + production intensity into monthly ESG reporting.",
  },
  {
    id: "adv-011",
    slug: "advanced-process-mining",
    name: "Advanced Process Mining",
    description: "AI-assisted bottleneck discovery and hidden flow inefficiency detection.",
    priority: "important",
    complexity: "high",
    adoptionPercent: 33,
    latencyMs: 740,
    roiPercent: 10.9,
    status: "pilot",
    recommendation: "Run weekly mining jobs and route top issues to RCA workflows.",
  },
  {
    id: "adv-012",
    slug: "federated-learning-platform",
    name: "Federated Learning Platform",
    description: "Cross-site collaborative model training without sharing raw data.",
    priority: "innovative",
    complexity: "high",
    adoptionPercent: 22,
    latencyMs: 1240,
    roiPercent: 8.6,
    status: "planned",
    recommendation: "Launch with predictive maintenance models across Atlas + Nova.",
  },
];

export const demoInnovationIdeas: InnovationIdea[] = [
  {
    id: "idea-001",
    title: "Autonomous Factory Orchestration",
    summary: "Self-optimizing scheduling and dispatching in real time across lines.",
    impactScore: 95,
    horizon: "mid_term",
    readiness: "prototype",
  },
  {
    id: "idea-002",
    title: "Predictive Demand-Coupled Planning",
    summary: "Demand forecasts auto-adjust production planning to reduce waste.",
    impactScore: 88,
    horizon: "near_term",
    readiness: "prototype",
  },
  {
    id: "idea-003",
    title: "Cross-Industry Benchmarking Network",
    summary: "Anonymous peer benchmarking for OEE, quality, and sustainability metrics.",
    impactScore: 81,
    horizon: "mid_term",
    readiness: "concept",
  },
  {
    id: "idea-004",
    title: "VR Factory Training Simulator",
    summary: "Immersive skill development with scenario-based operator training.",
    impactScore: 74,
    horizon: "mid_term",
    readiness: "concept",
  },
  {
    id: "idea-005",
    title: "Quantum Optimization Integration",
    summary: "Hybrid optimization engines for very large, constrained scheduling problems.",
    impactScore: 67,
    horizon: "long_term",
    readiness: "concept",
  },
  {
    id: "idea-006",
    title: "AI-Generated Maintenance Procedures",
    summary: "Condition-aware dynamic SOP generation from failure patterns.",
    impactScore: 83,
    horizon: "near_term",
    readiness: "prototype",
  },
  {
    id: "idea-007",
    title: "Machine Social Insight Network",
    summary: "Equipment-to-equipment sharing of performance and failure signatures.",
    impactScore: 72,
    horizon: "long_term",
    readiness: "concept",
  },
  {
    id: "idea-008",
    title: "Capacity Exchange Marketplace",
    summary: "Trusted platform for exchanging excess production capacity.",
    impactScore: 78,
    horizon: "mid_term",
    readiness: "concept",
  },
  {
    id: "idea-009",
    title: "AI Sustainability Advisor",
    summary: "Generates eco-efficient process modifications with quantified tradeoffs.",
    impactScore: 86,
    horizon: "near_term",
    readiness: "prototype",
  },
  {
    id: "idea-010",
    title: "Adaptive Compliance Copilot",
    summary: "Automatically maps changing regulations to plant evidence requirements.",
    impactScore: 84,
    horizon: "near_term",
    readiness: "prototype",
  },
  {
    id: "idea-011",
    title: "Predictive Workforce Planning",
    summary: "Anticipates skill gaps and recommends targeted training paths.",
    impactScore: 79,
    horizon: "mid_term",
    readiness: "validated",
  },
  {
    id: "idea-012",
    title: "Plug-and-Play Manufacturing Microservices",
    summary: "Composable app marketplace architecture for fast capability expansion.",
    impactScore: 82,
    horizon: "near_term",
    readiness: "prototype",
  },
];

const productionLines: ProductionLine[] = [
  {
    id: "line-alpha",
    facilityId: facility.id,
    name: "Alpha Stamping",
    status: "running",
    oee: 93.2,
    throughput: 342,
    targetThroughput: 360,
    yieldRate: 98.8,
  },
  {
    id: "line-bravo",
    facilityId: facility.id,
    name: "Bravo Assembly",
    status: "attention",
    oee: 88.4,
    throughput: 274,
    targetThroughput: 310,
    yieldRate: 97.1,
  },
  {
    id: "line-charlie",
    facilityId: facility.id,
    name: "Charlie Packaging",
    status: "maintenance",
    oee: 81.7,
    throughput: 198,
    targetThroughput: 250,
    yieldRate: 95.4,
  },
];

const equipment: Equipment[] = [
  {
    id: "eq-press-07",
    lineId: "line-alpha",
    name: "Servo Press 07",
    type: "Stamping Press",
    status: "running",
    healthScore: 96,
    utilization: 91,
    energyKw: 126,
    lastService: "2026-03-03T09:30:00Z",
    digitalTwinState: "Nominal torque curve",
  },
  {
    id: "eq-robot-12",
    lineId: "line-bravo",
    name: "Robot Cell 12",
    type: "Assembly Robot",
    status: "warning",
    healthScore: 78,
    utilization: 84,
    energyKw: 98,
    lastService: "2026-02-19T11:15:00Z",
    digitalTwinState: "Cycle time drift +4.1%",
  },
  {
    id: "eq-oven-03",
    lineId: "line-charlie",
    name: "Cure Oven 03",
    type: "Thermal Process",
    status: "maintenance",
    healthScore: 63,
    utilization: 66,
    energyKw: 154,
    lastService: "2026-01-28T14:45:00Z",
    digitalTwinState: "Thermal imbalance detected",
  },
  {
    id: "eq-vision-04",
    lineId: "line-bravo",
    name: "Vision Station 04",
    type: "Quality Inspection",
    status: "running",
    healthScore: 92,
    utilization: 88,
    energyKw: 41,
    lastService: "2026-03-09T08:00:00Z",
    digitalTwinState: "Inspection confidence stable",
  },
];

const alerts: Alert[] = [
  {
    id: "alert-001",
    equipmentId: "eq-oven-03",
    title: "Oven zone 2 overheating",
    severity: "critical",
    category: "Process",
    status: "open",
    createdAt: "2026-03-14T05:48:00Z",
    summary: "Temperature exceeded tolerance band for 8 minutes. Quality risk is rising.",
  },
  {
    id: "alert-002",
    equipmentId: "eq-robot-12",
    title: "Assembly cycle drift",
    severity: "high",
    category: "Performance",
    status: "investigating",
    createdAt: "2026-03-14T04:22:00Z",
    summary: "Predicted throughput miss of 11% if the current motion path remains unchanged.",
  },
  {
    id: "alert-003",
    equipmentId: "eq-vision-04",
    title: "Vision model confidence dip",
    severity: "medium",
    category: "Quality",
    status: "resolved",
    createdAt: "2026-03-13T20:16:00Z",
    summary: "Lighting variation corrected after recalibration.",
  },
];

const maintenance: MaintenancePrediction[] = [
  {
    id: "maint-001",
    equipmentId: "eq-oven-03",
    issue: "Exhaust fan bearing wear",
    confidence: 91,
    daysUntilService: 1,
    recommendedAction: "Inspect bearing assembly and replace fan cartridge during next planned stop.",
  },
  {
    id: "maint-002",
    equipmentId: "eq-robot-12",
    issue: "Axis 3 servo backlash",
    confidence: 84,
    daysUntilService: 4,
    recommendedAction: "Run backlash calibration and inspect coupling set screws.",
  },
  {
    id: "maint-003",
    equipmentId: "eq-press-07",
    issue: "Hydraulic pressure ripple",
    confidence: 67,
    daysUntilService: 9,
    recommendedAction: "Review accumulator charge level and monitor pressure variance trend.",
  },
];

const qualityEvents: QualityEvent[] = [
  {
    id: "quality-001",
    lineId: "line-alpha",
    batchCode: "AT-240314-A",
    defectCategory: "Surface blemish",
    defectRate: 0.8,
    firstPassYield: 99.1,
    status: "stable",
    checkedAt: "2026-03-14T05:20:00Z",
  },
  {
    id: "quality-002",
    lineId: "line-bravo",
    batchCode: "AT-240314-B",
    defectCategory: "Fastener torque miss",
    defectRate: 1.9,
    firstPassYield: 97.3,
    status: "watch",
    checkedAt: "2026-03-14T05:05:00Z",
  },
  {
    id: "quality-003",
    lineId: "line-charlie",
    batchCode: "AT-240314-C",
    defectCategory: "Cure variance",
    defectRate: 3.7,
    firstPassYield: 94.8,
    status: "intervention",
    checkedAt: "2026-03-14T04:40:00Z",
  },
];

export const demoData: DemoData = {
  facility,
  productionLines,
  equipment,
  alerts,
  maintenance,
  qualityEvents,
};

export function createDashboardSummary(data: DemoData) {
  const averageOee =
    data.productionLines.reduce((total, line) => total + line.oee, 0) /
    data.productionLines.length;
  const totalThroughput = data.productionLines.reduce(
    (total, line) => total + line.throughput,
    0,
  );
  const openAlerts = data.alerts.filter((alert) => alert.status !== "resolved").length;
  const meanHealth =
    data.equipment.reduce((total, item) => total + item.healthScore, 0) / data.equipment.length;

  return [
    {
      label: "Factory OEE",
      value: formatPercent(averageOee),
      change: "+2.4% vs last shift",
      tone: "positive" as const,
    },
    {
      label: "Hourly Throughput",
      value: formatNumber(totalThroughput),
      change: "18 units behind target",
      tone: "warning" as const,
    },
    {
      label: "Open Alerts",
      value: formatNumber(openAlerts),
      change: "1 critical escalation",
      tone: "critical" as const,
    },
    {
      label: "Mean Asset Health",
      value: formatPercent(meanHealth, 0),
      change: "2 assets need service planning",
      tone: "warning" as const,
    },
  ];
}

export function findEquipment(equipmentId: string): Equipment | undefined {
  return equipment.find((item) => item.id === equipmentId);
}

export function findLine(lineId: string): ProductionLine | undefined {
  return productionLines.find((item) => item.id === lineId);
}

export function latestQualitySignal(events: QualityEvent[]) {
  return [...events].sort((a, b) => (a.checkedAt < b.checkedAt ? 1 : -1))[0];
}
